name: Build Windows EXE (PyInstaller)

on:
  push:
    tags:
      - 'v*'         # если запушишь тег v1.0.0 — сделаем релиз с .exe
  workflow_dispatch: {}  # позволяет запустить руками из вкладки Actions

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconsole --onefile --name "AvitoPriceAnalyzer" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AvitoPriceAnalyzer.exe
          path: dist/AvitoPriceAnalyzer.exe   # ВАЖНО: именно такой путь для --onefile
          if-no-files-found: error

  release:
    needs: build-windows
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: AvitoPriceAnalyzer.exe
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AvitoPriceAnalyzer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
